### ISSUE TITLE
Feat analysis in FSL not working

### ISSUE THREAD

**Issue by tonygoldstone** [c3nl-neuraldynamics/c3nl_cluster#11]
Basic higher level Feat analyses in FSL are not running. 
No error message generated but analysis hangs before finished.
Log page reads as follows:

#!/bin/bash /apps/software/fsl/5.0.10/bin/feat /group/hormone/appetite/fsl_results/cohort/n71_lunch_intake/n71_cohort_HvO_corr_lunch_perc_REE_no_covariates_Z23_05.gfeat/cope1.feat/design.fsf -D /group/hormone/appetite/fsl_results/cohort/n71_lunch_intake/n71_cohort_HvO_corr_lunch_perc_REE_no_covariates_Z23_05.gfeat/cope1.feat -poststats 1 #!/bin/bash command=`cat ./.flame | head -$SLURM_ARRAY_TASK_ID | tail -1` ; exec $command #!/bin/bash /apps/software/fsl/5.0.10/bin/feat /group/hormone/appetite/fsl_results/cohort/n71_lunch_intake/n71_cohort_HvO_corr_lunch_perc_REE_no_covariates_Z23_05.gfeat/cope1.feat/design.fsf -D /group/hormone/appetite/fsl_results/cohort/n71_lunch_intake/n71_cohort_HvO_corr_lunch_perc_REE_no_covariates_Z23_05.gfeat/cope1.feat -I 1 -flame1 #!/bin/bash /apps/software/fsl/5.0.10/bin/feat /group/hormone/appetite/fsl_results/cohort/n71_lunch_intake/n71_cohort_HvO_corr_lunch_perc_REE_no_covariates_Z23_05.gfeat/cope1.feat/design.fsf -D /group/hormone/appetite/fsl_results/cohort/n71_lunch_intake/n71_cohort_HvO_corr_lunch_perc_REE_no_covariates_Z23_05.gfeat/cope1.feat -flame3

**Comment by petehellyer** [comment]
this appears to be the same problem as #6
