### ISSUE TITLE
launch failed requeued held

### ISSUE THREAD

**Issue by liamnestor** [c3nl-neuraldynamics/c3nl_cluster#12]
Problems completing some of the first level analyses in fls feat for a particular subject. I keep seeing the same message when I inspect my batchjobs - "launch failed requeued held." I never experienced this problem on the old cluster or have I experienced it on the other subject data I have processed on the new cluster. I have tried cancelling the job, regenerating the feat script, and starting it again - I still get the same message.

Any idea why this is happening?

Liam.

**Comment by eyalsoreq** [comment]
Fixed this you can re-submit all jobs

**Comment by petehellyer** [comment]
copy of #6
