### ISSUE TITLE
launch failed requeued held

### ISSUE THREAD

**Issue by chloechiou** [c3nl-neuraldynamics/c3nl_cluster#13]
I have the same issue as others -  got this problem when running the sbatch. Have tried scontrol release but the job still went back to 'launch failed requeued held'. 

Has anyone have found a solution? Or is there an alternative way/temporary way to run the data processing before this issue gets solved? e.g. fsl_sub -q verylong.q <job>...?

Thanks.

**Comment by eyalsoreq** [comment]
Fixed it by resetting all compute-nodes and then scontroling them back to idle mode 
Then you need to pipe all the jobid's and release them

**Comment by petehellyer** [comment]
mirror of #6
