### ISSUE TITLE
Permission denied for a directory I was added to - project ICCAM

### ISSUE THREAD

**Issue by liamnestor** [c3nl-neuraldynamics/c3nl_cluster#14]
I am still unable to access this project folder. Can you please grant me permissions?

Thank you,

Liam.

Original email from c3nl:

Dear lnestor, 

 You were just added to project ICCAM under group hormone by  on the c3nl cluster. 

 If for some reason you do not wish acsess to this folder please let us know. 

 BW 

C3nl Cluster Team

**Comment by tonygoldstone** [comment]
Can this be sorted asap. I cannot run a chmod -R 2750 command on the ICCAM folder under /group/hormone

**Comment by petehellyer** [comment]
This is the same as #9
