### ISSUE TITLE
Cannot open FSL or firefox

### ISSUE THREAD

**Issue by efroelofs** [c3nl-neuraldynamics/c3nl_cluster#15]
Hi, 

I'm trying to open firefox and FSL but it seems every time I try to open it, I get an error prompt or nothing happens.

When I try to open firefox:
[eroelofs@brodmann23d GNG]$ firefox 
Invalid MIT-MAGIC-COOKIE-1 keyError: cannot open display: localhost:24.0

When I try to open FSL: 
[eroelofs@brodmann23d GNG]$ fsl &                                              
[2] 3356                                                                        
bash: fsl: command not found 
And then nothing happens. 

I've tried opening it from this location: /group/hormone/ICCAM/controls_test_retest/GNG

Hope you can help!

Kind regards, 

Eline

**Comment by sdesimoni** [comment]
Hi Eline,

Try the following: 

(1) exit the cluster (type this into all terminal windows you have open, until you have exited the cluster completely) and then log back in. See if this resolves the problem.

(2) Make sure you have the following info in your bash_profile:

#Module loads
module load fsl/5.0.10

To change this, on the command line type: nano ~/.bash_profile and paste the couple of lines into the bash_profile

Then use ctrl X to exit this window (make sure you say Yes to saving the changes).

Then on the command line type: source ~/.bash_profile

This should allow you to open fsl without any problems

Sara

**Comment by efroelofs** [comment]
Hi Sara,


Thank you so much for your help, the second option worked perfectly!


Eline

________________________________
