### ISSUE TITLE
Dependency Never Satisfied - a FEAT (statistics stage?) issue

### ISSUE THREAD

**Issue by sdesimoni** [c3nl-neuraldynamics/c3nl_cluster#16]
Hi both,

I'm afraid there are still problems while running FEAT. This appears to crash while running FEAT stats/postats stages. All preprocessing appears to run normally. Lucia has run a single FEAT analysis too, and it crashes at a similar stage. 

The command I have run in /group/tbi/DREAM/SST_analysis/first_level/feat_configs/ is:

feat 67_SST1aV1.fsf

The output of my current attempt is in /home/sdesimoni/SST1a_067_v1+++.feat/

What the queue error looks like:

![screen shot 2017-07-07 at 10 33 21](https://user-images.githubusercontent.com/16757755/27952600-cab5e836-6300-11e7-9dc6-27d2bf9651d4.png)

Information from the FEAT r/home/sdesimoni/SST1a_067_v1+++.feat/report.html 

![screen shot 2017-07-07 at 10 33 05](https://user-images.githubusercontent.com/16757755/27952613-d1d595bc-6300-11e7-99e7-b54e5a5e8e83.png)

If you need more info, let me know

**Comment by tonygoldstone** [comment]
I have exactly the same problem when running a higher level Feat from Feat gui or running feat design.fsf without any use of squeue command in terminal.
This needs fixing asap. I have PhD and MSc students who are leaving imminently and cannot do any work as a result.
Thanks
Tony

**Comment by tonygoldstone** [comment]
For example if I try and run this design.fsf using Feat in gui or terminal it hangs and does not run the GLM. The cope1.feat creates loads of temporary files but then gets stuck. 

/group/hormone/appetite/fsl_results/cohort/n71_lunch_intake/n71_cohort_HvO_corr_lunch_perc_REE_no_covariates_Z23_05+.gfeat/design.fsf

No error message in log but at bottom there is an unusual text at bottom:

#!/bin/bash /apps/software/fsl/5.0.10/bin/feat /group/hormone/appetite/fsl_results/cohort/n71_lunch_intake/n71_cohort_HvO_corr_lunch_perc_REE_no_covariates_Z23_05+.gfeat/cope1.feat/design.fsf -D /group/hormone/appetite/fsl_results/cohort/n71_lunch_intake/n71_cohort_HvO_corr_lunch_perc_REE_no_covariates_Z23_05+.gfeat/cope1.feat -poststats 1 #!/bin/bash /apps/software/fsl/5.0.10/bin/feat /group/hormone/appetite/fsl_results/cohort/n71_lunch_intake/n71_cohort_HvO_corr_lunch_perc_REE_no_covariates_Z23_05+.gfeat/cope1.feat/design.fsf -D /group/hormone/appetite/fsl_results/cohort/n71_lunch_intake/n71_cohort_HvO_corr_lunch_perc_REE_no_covariates_Z23_05+.gfeat/cope1.feat -stop #!/bin/bash /apps/software/fsl/5.0.10/bin/feat /group/hormone/appetite/fsl_results/cohort/n71_lunch_intake/n71_cohort_HvO_corr_lunch_perc_REE_no_covariates_Z23_05+.gfeat/cope1.feat/design.fsf -D /group/hormone/appetite/fsl_results/cohort/n71_lunch_intake/n71_cohort_HvO_corr_lunch_perc_REE_no_covariates_Z23_05+.gfeat/cope1.feat -flame3 #!/bin/bash /apps/software/fsl/5.0.10/bin/feat /group/hormone/appetite/fsl_results/cohort/n71_lunch_intake/n71_cohort_HvO_corr_lunch_perc_REE_no_covariates_Z23_05+.gfeat/cope1.feat/design.fsf -D /group/hormone/appetite/fsl_results/cohort/n71_lunch_intake/n71_cohort_HvO_corr_lunch_perc_REE_no_covariates_Z23_05+.gfeat/cope1.feat -I 1 -flame1 #!/bin/bash command=`cat ./.flame | head -$SLURM_ARRAY_TASK_ID | tail -1` ; exec $command

**Comment by eyalsoreq** [comment]
Just a quick update (mostly so you know we are taking you seriously) 
For the slim possibility that this is permission related I ran the command as root. 
It processed the three stages and stopped at feat4 in a similar way to your original report. 
I have to finish some stuff for myself before I have time to dive into the FSL abyss but I am preparing myself mentally

**Comment by sdesimoni** [comment]
![screen shot 2017-07-12 at 14 42 08](https://user-images.githubusercontent.com/16757755/28120611-74401706-6710-11e7-9703-75ee459e390d.png)

Hello -update from my side. 

I have tried running .fsf single FEATs set up using old FSL version 5.0.9 and they don't work using either the: feat <.fsf> command or by loading the .fsf into the FEAT GUI. 

As you can see from above, it still ends at the feat3_stats stage. The error logs state this: 

slurmstepd: error: *** JOB 601893 ON compute-2-4 CANCELLED AT 2017-07-12T14:31:24 DUE TO TIME LIMIT ***

JOB 601893 is the feat3 stage.

I realise this is probably an issue with FSL 5.0.9 now (so may not be worth pursuing), so will try to run this entirely with FSL 5.0.10 as Tony has managed to run FEAT now with this version. 

I will update you with the outcome.

**Comment by Lmli** [comment]
Hello,

I'm sorry to report that FEAT is not working for us.

My student set up a FEAT and tried to run it and got the DependencyNeverSatisfied error again.

Relevant points:
- She set up a brand new FEAT config with the GUI rather than changing one I'd made previously on the old cluster
- She used a NIFTI file that was downloaded and processed entirely on the new Cluster using fix 5.10

Thanks,
Lucia

**Comment by sdesimoni** [comment]
Hello - another update on my previous note:

I set up the FEAT analysis in the FSL 5.0.10 GUI and the error is still the same.

I.e. it still stops at feat_stat3 and I get the following error in the output directory:

/home/sdesimoni/feat_test.feat/logs

slurmstepd: error: *** JOB 602025 ON compute-2-4 CANCELLED AT 2017-07-12T15:20:54 DUE TO TIME LIMIT ***

**Comment by petehellyer** [comment]
@sdesimoni I've opened a new ticket for this #19 
@Lmli this is likely the same issue as #6

**Comment by Lmli** [comment]
@petehellyer /home/uk215/POST/SST/NIFTI/new/testfeat

thanks dude

**Comment by petehellyer** [comment]
Ok, yes, this is the same as #19. Hopefully a fix shortly.

**Comment by Lmli** [comment]
thanks :)
