### ISSUE TITLE
Launch Failed Requeued held -- again

### ISSUE THREAD

**Issue by SebastianPopescu** [c3nl-neuraldynamics/c3nl_cluster#17]
Hi guys,

Since you fixed the initial complaints about this yesterday, I have managed to submit some jobs which are running at the moment but now I am getting again the same problem.(Launch failed)

Compute-2-2 is down, maybe it needs to be drained

**Comment by petehellyer** [comment]
Same issue as #6, investigations continue - but I'm on a plane right now.
