### ISSUE TITLE
LCmodel software

### ISSUE THREAD

**Issue by MariaICL** [c3nl-neuraldynamics/c3nl_cluster#2]
Software was previously installed in the old cluster (there was a folder in  /share/apps/LCmodel, where the main lcmgui was, and individual folders in people's home directories, in /home/.lcmodel). 

This is a licensed software, I emailed the creator about how to get the license transferred to a new machine, emails are below.

The issue is that all of those instructions are meant for a single user, not for a setup like ours. I believe that the original solution in the old cluster was to create an user specifically to run LCmodel, but at some point this got improved, and anyone could access it from their own account. I think this involved writing some code to make this happen, but I don't know the details.

> From:

> Stephen Provencher <sp@lcmodel.ca>
>Sent: 31 May 2017 16:41
>To: Yanez Lopez, Maria
>Cc: Hellyer, Peter John
>Subject: Moving your LCModel license
 
>Dear Maria,

>An LCModel license can be transferred once to a replacement computer at
>no charge.  If this replacement is ever replaced, you would have to
>purchase an additional license (at the additional 50% discount for an
>additional license for the same group).  More information is on
>http://lcmodel.ca/lcm-license.shtml, under "License Terms".

>However, this is only for future planning.  You have your free transfer
>left.  You have 2 options:

>(1) The entire LCModel package is in the directory ~/.lcmodel/.  You
could copy the entire ~/.lcmodel/ directory tree to your new
computer.  This way, you preserve perfect compatibility with your old
results, and you preserve your settings, results, basis sets, etc.

>(2) Alternatively, you could download and install the latest LCModel
package from http://lcmodel.ca/lcm-test.shtml.  You would then copy over
your basis sets into ~/.lcmodel/basis-sets/ and maybe other directories,
such as ~/.lcmodel/saved/.

>In case (1), you run an analysis on your new computer.  LCModel
stops, telling you that you need a license and also outputs the file
~/.lcmodel/data-for-licensing.  In case (2),
~/.lcmodel/data-for-licensing is automatically produced during the
installation.  In either case, you send

>  ~/.lcmodel/data-for-licensing

>to me, and we send you the license file unique to your new computer.
Please note that ~/.lcmodel/data-for-licensing must be produced on the
computer that you want to license.  The license file that we send will
only work on this computer.

>When LCModel is running on your new computer, you permanently remove
LCModel from your old computer.

>With best regards,
>Stephen
__________________________
>Stephen Provencher, PhD
>LCMODEL Inc
>Suite 1007
>100 Lakeshore Road East
>Oakville, Ontario  L6J 6M9
>Canada
>www.lcmodel.ca
>sp@lcmodel.ca

>On 2017-05-31 09:20 AM, Yanez Lopez, Maria wrote:
> Dear Stephen,
>
> We have the LCmodel software installed in a linux system that is going
> to be decommissioned. We would like to install it in another
> linux system, to carry on using it, could you advise on how we should go
> about it?
>
> Thank you in advance,
>
> Maria.
>
> Maria Yanez Lopez, PhD
> C3NL
> Division of Brain Sciences
> Department of Medicine
> Imperial College London

**Comment by petehellyer** [comment]
merge with https://github.com/c3nl-neuraldynamics/c3nl_cluster/issues/3
