### ISSUE TITLE
Jobs get killed

### ISSUE THREAD

**Issue by SebastianPopescu** [c3nl-neuraldynamics/c3nl_cluster#20]
Hi

I had two jobs which were running for a day and they got killed with the following error message:

/tmp/slurmd/job603995/slurm_script: line 9:  4727 Killed 

Do you know what's happening here? I assume they were not manually killed by admins

**Comment by petehellyer** [comment]
When did they die? Occasionally the nodes need to be rebooted, but if that happened they should have been requeued.

**Comment by petehellyer** [comment]
Assume all is fine. Closing
