### ISSUE TITLE
Cannot log onto cluster

### ISSUE THREAD

**Issue by liamnestor** [c3nl-neuraldynamics/c3nl_cluster#21]
I was on the cluster this morning. It became very slow. I closed out and now cannot log back in via putty - it first tells me access is denied after entering passord and then closes the network connection when I try a second time to enter my password -  see attached screenshot. 

Any ideas?

Thank you,

Liam.

![screenshot](https://user-images.githubusercontent.com/29919687/28422309-898985a2-6d5f-11e7-93e9-43c40c4c7ed7.png)

**Comment by petehellyer** [comment]
yep, there is an ongoing problem with our authentication server that I am working on right now :)

**Comment by liamnestor** [comment]
Okay so - many thanks - I will leave you in peace to work it out.

Liam.

**Comment by petehellyer** [comment]
Closing this as it should now be fixed. Hopefully you have received a new password by email.
