### ISSUE TITLE
LC model display issues

### ISSUE THREAD

**Issue by MariaICL** [c3nl-neuraldynamics/c3nl_cluster#22]
While the LCmodel is now working and saving the results in the "saved" folder of your choosing (ps file), it is still not displaying them in evince (blank ps file) and is giving an error (invalidaccess=-7), do you know what this might be?
![screenshot - 260717 - 12 12 54](https://user-images.githubusercontent.com/18559344/28618529-9e9d936a-71fc-11e7-9751-1f14baa2c067.png)

**Comment by petehellyer** [comment]
this is an issue with evince (not LCmodel) - god only knows what the problem is, various tickets open on the web blame a wide range of different things.

**Comment by MariaICL** [comment]
Ok, so if I cannot see pdfs on the cluster, I tried to create a symbolic link to the /lcmodel folder so that I can see them when I mount it in my local computer. 
Could you tell me why this does not work?
`ln -s /lcmodel/ lcmodel`

![screen shot 2017-07-27 at 14 19 00](https://user-images.githubusercontent.com/18559344/28672078-97054d16-72d6-11e7-8d39-f9471566e129.png)

**Comment by MariaICL** [comment]
It's working now
