### ISSUE TITLE
the demise of randomise

### ISSUE THREAD

**Issue by sdesimoni** [c3nl-neuraldynamics/c3nl_cluster#23]
Hello,

This may be related to slurm issues but just thought I would let you know that randomise isn't running on the cluster either:

I have tried running this through FEAT - see output in this folder:

/group/tbi/DREAM/SST_analysis/first_level/postFIX/FFX/Cope6_GroupFEAT_57subj_randomise.gfeat

I have checked the logs but it doesn't seem to produce an error apart from the 'Dependency Never Satisfied' in the queue

![screen shot 2017-07-26 at 14 41 58](https://user-images.githubusercontent.com/16757755/28624289-9dda509e-7210-11e7-9fdf-7df3656edc13.png)

It stops at this command:

![screen shot 2017-07-26 at 14 42 48](https://user-images.githubusercontent.com/16757755/28624333-c139b8d6-7210-11e7-87c8-72efd2fc9313.png)

**Comment by Lmli** [comment]
NB: the randomise command on its own works, if typed into the command line:

e.g.
randomise -i origPNAS_DMN_CvS/dr_stage2_ic0000.nii.gz -o test -d ttest.mat -t ttest.con -m /home/lli/CONTROLS/SST/ROIs/bin/PNAS_DMN_3mm.nii.gz -n 10 -T

So.... think it might be a FEAT running stats issue. Especially because my group feat is not working.

**Comment by sdesimoni** [comment]
Yes, randomise also works using fsl_sub before the command which is great. 

I agree, I think randomise only doesn't work if wrapped up in FEAT or the dual_regression script.

Will give the dual regression a go soon - maybe end of August as I am away next week!

**Comment by petehellyer** [comment]
I *THINK* I have fixed this finally. Would be good if someone could check. Am also emailing Sara and Tony.

**Comment by petehellyer** [comment]
see ticket #33
