### ISSUE TITLE
launch failed requeued held

### ISSUE THREAD

**Issue by SebastianPopescu** [c3nl-neuraldynamics/c3nl_cluster#24]
Tried to submit multiple jobs this morning and all I get is the following error:

launch failed requeued held

**Comment by SebastianPopescu** [comment]
it still looks like it's not working

**Comment by petehellyer** [comment]
Ok, I know what is wrong here, will take an hour or so to fix.

**Comment by petehellyer** [comment]
Now fixed.

For those who are bothered - this was because the compute nodes failed to re-register with IPA following an image reboot. On top of that, clocks on the nodes were way out of sync which prevented submission.
