### ISSUE TITLE
Problem completing first level analyses in fsl feat

### ISSUE THREAD

**Issue by liamnestor** [c3nl-neuraldynamics/c3nl_cluster#28]
I am having problems completing the first level analyses in fsl feat - it appears to commence the analyses but just seems to get stuck? I don't seem to be able to see my batch jobs for these analyses either? 

Any ideas?

Liam.

**Comment by petehellyer** [comment]
Hi Liam, 

This is a known problem, which we're working on :)

Cheers

Pete

**Comment by petehellyer** [comment]
I've made changes that should fix this.

**Comment by petehellyer** [comment]
See #23
