### ISSUE TITLE
LCModel 

### ISSUE THREAD

**Issue by inesviolante** [c3nl-neuraldynamics/c3nl_cluster#3]
LCModel is not installed in brodmann23d.

In brodmann39 there was a folder in  /share/apps/LCmodel, where the main lcmgui was, and individual folders in people's home directories, in /home/.lcmodel

This is a licensed software, I emailed the creator about how to get the license transferred to a new machine, emails are below.

The issue is that all of those instructions are meant for a single user, not for a setup like ours. I believe that the original solution in the old cluster was to create an user specifically to run LCmodel, but at some point this got improved, and anyone could access it from their own account. I think this involved writing some code to make this happen, but I don't know the details.

> From:

> Stephen Provencher <sp@lcmodel.ca>
>Sent: 31 May 2017 16:41
>To: Yanez Lopez, Maria
>Cc: Hellyer, Peter John
>Subject: Moving your LCModel license
 
>Dear Maria,

>An LCModel license can be transferred once to a replacement computer at
>no charge.  If this replacement is ever replaced, you would have to
>purchase an additional license (at the additional 50% discount for an
>additional license for the same group).  More information is on
>http://lcmodel.ca/lcm-license.shtml, under "License Terms".

>However, this is only for future planning.  You have your free transfer
>left.  You have 2 options:

>(1) The entire LCModel package is in the directory ~/.lcmodel/.  You
could copy the entire ~/.lcmodel/ directory tree to your new
computer.  This way, you preserve perfect compatibility with your old
results, and you preserve your settings, results, basis sets, etc.

>(2) Alternatively, you could download and install the latest LCModel
package from http://lcmodel.ca/lcm-test.shtml.  You would then copy over
your basis sets into ~/.lcmodel/basis-sets/ and maybe other directories,
such as ~/.lcmodel/saved/.

>In case (1), you run an analysis on your new computer.  LCModel
stops, telling you that you need a license and also outputs the file
~/.lcmodel/data-for-licensing.  In case (2),
~/.lcmodel/data-for-licensing is automatically produced during the
installation.  In either case, you send

>  ~/.lcmodel/data-for-licensing

>to me, and we send you the license file unique to your new computer.
Please note that ~/.lcmodel/data-for-licensing must be produced on the
computer that you want to license.  The license file that we send will
only work on this computer.

>When LCModel is running on your new computer, you permanently remove
LCModel from your old computer.

>With best regards,
>Stephen

**Comment by petehellyer** [comment]
I worked on this at the weekend - the changes I made to make it work generally on the old cluster have been ported over to the new one

You 'theoretically' should be able to run now by loading LCmodel though modules, and then hitting lmgui.

I haven't installed a new licence though, as I don't have it.

**Comment by MariaICL** [comment]
I could open lcmgui, but I could not load any data, because the folders are not showing up on the gui, and when I manually put the paths, the files do not show up either, so I cannot select them. 
Not sure what is going on...

**Comment by petehellyer** [comment]
can you screenshot?

**Comment by MariaICL** [comment]
![screen shot 2017-06-20 at 14 45 13](https://user-images.githubusercontent.com/18559344/27336334-1d485d6e-55c7-11e7-8a4b-c32370db2cd1.png)

**Comment by MariaICL** [comment]
In that folder there are files of the right format, but they are not showing, even when I say show all files.

**Comment by MariaICL** [comment]
Sorry, the folder is actually /home/myanezl2/MRS, but same thing happens

**Comment by petehellyer** [comment]
weird, it doesn't seem to like mounted folders at all. I'll have a think about it.

**Comment by inesviolante** [comment]
Hi,
I have the same issue...
I wonder whether it would be better to delete this LCModel (copied from the old cluster) and do a fresh install??

**Comment by petehellyer** [comment]
not convinced a reinstall would help with this one - I'm pretty sure I know what the problem is. The difficulty is in knowing not being > than solving.

**Comment by MariaICL** [comment]
Hi Pete,
Have there been any changes on this?

**Comment by petehellyer** [comment]
I'll create a folder locally on the head node to stage data from - the problem is that TcL refuses to navigate NFS mounted directories.

**Comment by MariaICL** [comment]
Ah, ok, please let me know which folder and I can put all the MRS data there.

**Comment by inesviolante** [comment]
Hello!
Any updates on this? Do we have a folder now?
I have some MRS to analyse.
Thank you!!

**Comment by petehellyer** [comment]
folder created at /lcmodel which has ownership root:tbi and chmodded as 770.

**Comment by petehellyer** [comment]
Note, You should stage files into this, as unlike the home directories, there's pretty limited space on that disk.

**Comment by MariaICL** [comment]
I just tried it, I got an error:

cp: cannot stat \u2018*table\u2019: No such file or directory
/home/myanezl2/.lcmodel/temp/18d-16h-15m-09s-12178pid/outputScript: line 14: evince: command not found

Could you install evince, maybe?

**Comment by MariaICL** [comment]
In any case, then I get a message saying that I need to send to Provencher the automatically created file ~/.lcmodel/data-for-licensing

Should this file now be found in /apps/software/lcmodel/std?

**Comment by inesviolante** [comment]
I think I've asked this. But wouldn't it be easier to make a fresh install? 
As it seems that some of the files no longer exist and we might get issues with the ones that are still there (from previous version).

**Comment by MariaICL** [comment]
Any updates? This is a screenshot of the problem:
![screen shot 2017-07-25 at 15 50 16](https://user-images.githubusercontent.com/18559344/28578245-08ce2666-7151-11e7-8192-2d1741852fc6.png)

**Comment by petehellyer** [comment]
I've removed the symlink to the licence from your folder. try again, and hopefully it should generate the data-for-licencing file in ~/.lcmodel/data-for-licencing this needs to be sent to the lcmodel guy.

**Comment by MariaICL** [comment]
You mean here? There is nothing there...
![screen shot 2017-07-25 at 16 29 27](https://user-images.githubusercontent.com/18559344/28580121-81043ca6-7156-11e7-98ef-8505a012bd8c.png)

**Comment by petehellyer** [comment]
Did LCmodel provide any errors?

**Comment by MariaICL** [comment]
Same as the last screenshot

**Comment by MariaICL** [comment]
It also complains that evince is not installed, but this is another problem I think

**Comment by MariaICL** [comment]
![screen shot 2017-07-25 at 16 37 55](https://user-images.githubusercontent.com/18559344/28580534-a9c5f5c0-7157-11e7-94e3-49d7d94b6da5.png)

**Comment by petehellyer** [comment]
evince now installed. Have changed startup script (I was too clever for my own good) run again, see if it generates the file (make sure to close and re-open entirely)

**Comment by MariaICL** [comment]
Now the LCmodel screen looks completely different, it said that I did not have a license and gave me two options:
1) Test my data preparation
2) Run test data

The first one opened an evince window with "Loading", nothing ever showed up
The second, I got an error:
![screen shot 2017-07-25 at 16 52 56](https://user-images.githubusercontent.com/18559344/28581452-251b64c4-715a-11e7-8374-014073e549ae.png)

The licensing file did not get created.

**Comment by petehellyer** [comment]
ok, so I think we're getting closer.....
Try again now.

**Comment by MariaICL** [comment]
Same thing as before. I am adding more screenshots:
![screen shot 2017-07-25 at 17 18 15](https://user-images.githubusercontent.com/18559344/28582480-6fecda7a-715d-11e7-95cf-9ee6c5177eb9.png)
![screen shot 2017-07-25 at 17 17 59](https://user-images.githubusercontent.com/18559344/28582488-76c9718c-715d-11e7-870c-f4832295cff9.png)

**Comment by MariaICL** [comment]
File did not get created, evince did not print anything in options 1 or 2

**Comment by petehellyer** [comment]
have emailed you the data-for-licencing file.

**Comment by MariaICL** [comment]
Oh, great! I will send it to Provencher right away, was I doing something stupid then?

**Comment by petehellyer** [comment]
new licence file now in place. Hopefully this solves issues.

**Comment by MariaICL** [comment]
While the LCmodel is saving the results in the "saved" folder of your choosing (ps file), it is not displaying them in evince (blank ps file) and is giving an error (invalidaccess=-7), do you know what this might be?

![screenshot - 260717 - 12 12 54](https://user-images.githubusercontent.com/18559344/28618412-3554e994-71fc-11e7-839b-e7269998a9d6.png)
