### ISSUE TITLE
Submitting Matlab jobs to the job manager

### ISSUE THREAD

**Issue by james-cole** [c3nl-neuraldynamics/c3nl_cluster#30]
Trying and failing to run some SPM processes on the compute nodes using SLURM. Seems to be a problem with License Manager on the compute nodes. Anyone else had a similar problem?

Any thoughts? Here's the error:

MATLAB is selecting SOFTWARE OPENGL rendering.
License checkout failed.
License Manager Error -15
MATLAB is unable to connect to the license server. 
Check that the license manager has been started, and that the MATLAB client machine can communicate
with the license server.

Troubleshoot this issue by visiting: 
http://www.mathworks.com/support/lme/R2016b/15

Diagnostic Information:
Feature: MATLAB 
License path: /home/jcole/.matlab/R2016b_licenses:/apps/software/matlab/2016b/licenses/license.dat:/apps/software/
matlab/2016b/licenses/network.lic 
Licensing error: -15,570. System Error: 115

**Comment by petehellyer** [comment]
Fixed (via email)
