### ISSUE TITLE
mrtrix & fslsub

### ISSUE THREAD

**Issue by Nialljb** [c3nl-neuraldynamics/c3nl_cluster#32]
**Command run:**

for i in `cat $root/ISMRM/subj.txt`; do
#mkdir /home/nbourke/ISMRM/$i
#cp /source/HCP/$i/T1w/T1w_acpc_dc_restore_brain.nii.gz /home/nbourke/ISMRM/$i/
fsl_sub -N 5ttgen -l /home/nbourke/ISMRM/logs/ 5ttgen fsl /home/nbourke/ISMRM/$i/T1w_acpc_dc_restore_brain.nii.gz /home/nbourke/ISMRM/$i/5TT.mif -premasked
done

**It runs for about 15min before producing this error:**
 /apps/software/fsl/5.0.10/bin/fsl_sub: line 287: bc: command not found

I will try via sbatch now. On a side not I couldnt run this with the input directly from /source/HCP, I assume this has something to do with it not being a fan of writing temp files there or something?

**Comment by petehellyer** [comment]
so, just at the current second, /source doesnt work over the compute nodes, but will shortly (my main job for the day).

bc clearly missing on compute nodes, will be added to the image post haste.

**Comment by Nialljb** [comment]
Good stuff! The bc error pops up again even if I have submitted through SBATCH. Is there some sort of magic occurring which is calling fsl_sub from the mrtrix command and leading to the same error or is there something else going on?

**Comment by petehellyer** [comment]
This should now work, I would hope.

**Comment by petehellyer** [comment]
bc now installed on compute nodes, believed to be fixed.
