### ISSUE TITLE
Feat 1st level still not working despite using FSL 5.0.9

### ISSUE THREAD

**Issue by tonygoldstone** [c3nl-neuraldynamics/c3nl_cluster#33]
I cannot still run 1st Feat analyses
I have tried using FSL 5.0.9 rather than 5.0.10 but still does not work.
Error message: 
slurmstepd: error: *** JOB 624755 ON compute-1-4 CANCELLED AT 2017-08-01T18:33:36 DUE TO TIME LIMIT *** child process exited abnormally while executing "if { [ catch { for { set argindex 1 } { $argindex < $argc } { incr argindex 1 } { switch -- [ lindex $argv $argindex ] { -I { incr arginde..." (file "/apps/software/fsl/5.0.9/bin/feat" line 309) 

I tried running as a single feat in command line rather than as a multitude of scripted feat analysis but still not work
Thanks
Tony

**Comment by tonygoldstone** [comment]
Other error emssage in report_log

Error encountered while running in main feat script, halting. child process exited abnormally #!/bin/bash /apps/software/fsl/5.0.9/bin/feat /group/hormone/ICCAM/controls_test_retest/I19/01/func/gng/gng1/analysis3_1sec_final.feat/design.fsf -D /group/hormone/ICCAM/controls_test_retest/I19/01/func/gng/gng1/analysis3_1sec_final.feat -I 1 -init #!/bin/bash /apps/software/fsl/5.0.9/bin/feat /group/hormone/ICCAM/controls_test_retest/I19/01/func/gng/gng1/analysis3_1sec_final.feat/design.fsf -D /group/hormone/ICCAM/controls_test_retest/I19/01/func/gng/gng1/analysis3_1sec_final.feat -stop #!/bin/bash /apps/software/fsl/5.0.9/bin/feat /group/hormone/ICCAM/controls_test_retest/I19/01/func/gng/gng1/analysis3_1sec_final.feat/design.fsf -D /group/hormone/ICCAM/controls_test_retest/I19/01/func/gng/gng1/analysis3_1sec_final.feat -I 1 -prestats #!/bin/bash /apps/software/fsl/5.0.9/bin/feat /group/hormone/ICCAM/controls_test_retest/I19/01/func/gng/gng1/analysis3_1sec_final.feat/design.fsf -D /group/hormone/ICCAM/controls_test_retest/I19/01/func/gng/gng1/analysis3_1sec_final.feat -I 1 -stats #!/bin/bash /apps/software/fsl/5.0.9/bin/feat /group/hormone/ICCAM/controls_test_retest/I19/01/func/gng/gng1/analysis3_1sec_final.feat/design.fsf -D /group/hormone/ICCAM/controls_test_retest/I19/01/func/gng/gng1/analysis3_1sec_final.feat -poststats 0

**Comment by petehellyer** [comment]
Hopefully now fixed....

**Comment by petehellyer** [comment]
Tested by Tony, believed fixed (missing dependency 'file' on compute-nodes)

**Comment by sdesimoni** [comment]
Hi,

My first level FEAT hasn't worked, but I will try this again tomorrow with a different method. 

Tony are you using fsl 5.0.9 or 5.0.10?

Sara

**Comment by petehellyer** [comment]
Can you point me at it?

Cheers

Pete

**Comment by sdesimoni** [comment]
/home/sdesimoni/feat_test5.feat

**Comment by tonygoldstone** [comment]
5.0.10
--------------------------------------------------------
Dr Tony Goldstone MA MRCP PhD

Head PsychoNeuroEndocrinology Research Group, Senior Clinical Research Fellow,
Neuropsychopharmacology Unit, Centre for Psychiatry, and Computational, Cognitive and Clinical Neuroimaging Laboratory,
Division of Brain Sciences, Imperial College London

Consultant Endocrinologist, Imperial College Healthcare NHS Trust

Postal Address:
Room E313, C3NL, 3rd Floor Burlington Danes Building
Hammersmith Hospital Campus
Imperial College London
Du Cane Road
London W12 0NN
United Kingdom

Tel:  +44 20 7594 5989
Mobile: +44 7958 612893
Fax: +44 20 7594 8921
E-mail: tony.goldstone@imperial.ac.uk<mailto:tony.goldstone@imperial.ac.uk>

Clinical Secretary: +44 20 3313 4823

Web: www.imperial.ac.uk/people/tony.goldstone<http://www.imperial.ac.uk/people/tony.goldstone>​
Twitter: @TonyGoldstone
Skype: tgoldstone







On 17 Aug 2017, at 17:01, sdesimoni <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

My first level FEAT hasn't worked, but I will try this again tomorrow with a different method.

Tony are you using fsl 5.0.9 or 5.0.10?

Sara
