### ISSUE TITLE
dcm2nii new version

### ISSUE THREAD

**Issue by Lmli** [c3nl-neuraldynamics/c3nl_cluster#34]
Hi Eyal & Pete,

Please could you download the newer version of dcm2nii (dcm2niix) onto the cluster? Both Gus & I have found that dcm2nii (old version) sometimes produces an upside DTI file (dcm and nii header info all correct) so we think it might be a conversion problem. Using the new command dcm2niix seems to produce the correct orientation of images.

https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Download

Many thanks,
Lucia

**Comment by petehellyer** [comment]
done - should be in 'module load mricroGL'

**Comment by GusZimmerman** [comment]
Hi- a heads up that the default version (2017) does not load dcm2niix and module load mricroGL/5May2016 is required
