### ISSUE TITLE
DTITK not working due to bc using srun?

### ISSUE THREAD

**Issue by GusZimmerman** [c3nl-neuraldynamics/c3nl_cluster#35]
Hi!
Part of the DTITK pipeline isn't working, giving the following error:
/apps/software/dtitk/2.3.1//scripts/dti_diffeomorphic_reg: line 123: bc: command not found
/apps/software/dtitk/2.3.1//scripts/dti_diffeomorphic_reg: line 124: bc: command not found
/apps/software/dtitk/2.3.1//scripts/dti_diffeomorphic_reg: line 126: [: too many arguments

Which in turn corresponds to these lines in the dti_diffeomorphic_reg script:
isjacmingood=`echo "$jacmin > ${jaclimit[0]}" | bc`
isjacmaxgood=`echo "$jacmax < ${jaclimit[1]}" | bc`

I can run bc on the headnode, but not using srun which I think is the issue- any way to workaround this?

Thanks.

**Comment by petehellyer** [comment]
should now be fixed
