### ISSUE TITLE
unable to access b23d

### ISSUE THREAD

**Issue by Lmli** [c3nl-neuraldynamics/c3nl_cluster#39]
Hi,

Several of us have all tried to access the cluster (either from anew, or after it froze), but cannot even ssh into it at the moment... is there work going on that's making the cluster inaccessible?

Thanks,
Lucia

**Comment by celiademarchi** [comment]
It's down again at 3pm on Wednesday 23rd of August. Similar pattern and time as yesterday, it became very very slow and then went down.

**Comment by inesviolante** [comment]
It's working now!
