### ISSUE TITLE
FSL FEAT - error associated with recognising text files (e.g. for EVs) 

### ISSUE THREAD

**Issue by sdesimoni** [c3nl-neuraldynamics/c3nl_cluster#4]
Hey guys,

I am experiencing problems running FEAT analyses on BA23d. I am running these within the /group/tbi/DREAM/SST_analysis folders. 

I create a .fsf file to set up the first-level analysis for one subject, including the model set up (in this case to analyse the Stop-Signal task). The command I used to run this is the following:

feat subject1.fsf

The error that I (and Lucia on her data) is associated with the text files that describe the EVs included in the model (see attached image). This error does not appear to be a permissions issue as I ran the specific command on the command line within the FEAT directory and it worked. It only appears to break down when the above command is used. 

This may be an issue with version 5.0.10 of FSL, however I have not found anything online to indicate that this is the case. 

Any thoughts of why this may be happening would be awesome. Happy to post more info if necessary. 

![txtfile_featerror](https://user-images.githubusercontent.com/16757755/27334592-b1b0f642-55c1-11e7-8735-5a19a9265375.png)

**Comment by petehellyer** [comment]
Ok, this problem is quite straight-forward. The compute nodes simply were missing a dependency on a program called 'file'

I'm re-building the compute nodes now and this should theoretically be fixed in the next hour or so

**Comment by petehellyer** [comment]
This should now be resolved, please do have a check

**Comment by sdesimoni** [comment]
Ok great, will have a look and let you know

**Comment by sdesimoni** [comment]
Ok this has definitely solved the text file issue but it now seems to be stuck on something else (it may be a memory issue) - I did have a problem that when running a lot of FEATs in one go, the log would show 'still running' even though there was no actual error. However, this usually resolved if not many things were being run at the same time. Will see tomorrow, once Lucia's FEATs have stopped running....

**Comment by Lmli** [comment]
Hi Pete, Sara,

I started running a higher level feat yesterday at approx 4pm. There are 11 copes within that. Previously, this would take about 30mins-1hour to do 2-3 such feats. It is still currently running, and the log does not show up any error messages:

![screen shot 2017-06-21 at 10 08 10](https://user-images.githubusercontent.com/29597717/27377155-1482bd6e-566c-11e7-9f41-3f50b5348035.png)

I also do not have the "Dependencies never satisfied" note next to my job IDs on squeue (I got this error when I tried to run feats last week on the new cluster).

Indeed, I have this:

![screen shot 2017-06-21 at 10 08 46](https://user-images.githubusercontent.com/29597717/27377198-357fccd2-566c-11e7-849c-c3c29e6667e3.png)

Indeed, I do wonder if the cluster/ the headnode has become clogged up, and so the feat isn't running simply because something else is ahead of it in the queue? (Which is problematic in itself...)

Thank you,
Lucia

**Comment by sdesimoni** [comment]
Thanks Lucia! My update is that I tried running a first-level FEAT (yesterday and today) but it appears to get stuck at the stats stage (Ev text file problem solved however). 

My queue info does state 'DependencyNeverSatisfied' although there is no error in the report log as it just states it is 'still running'.

![screen shot 2017-06-21 at 10 33 54](https://user-images.githubusercontent.com/16757755/27377664-8a2d8cd2-566d-11e7-80df-5fc4a54767b9.png)

**Comment by petehellyer** [comment]
So, Lucias thing - this is an internal network problem rather than a feat problem - I've released all of your jobs, so they should in theory run to completion.

**Comment by petehellyer** [comment]
Sara, this means that something that job was waiting on bummed out somehow. Can you point me at this analysis and I'll look in more detail.

**Comment by sdesimoni** [comment]
Hey Pete, I'm not sure there is anything wrong with this analysis because I have run it locally and it worked fine. Also the 'DependencyNeverSatisfied' also appeared sporadically when I was running multiple  fixed-effects analyses a few weeks ago. This resolved just by re-running each analysis individually, which makes me think it may be due memory issues? 

However, I can believe that I made a mistake somewhere too as I have run these things a hundred different ways. I will double check. 

The test analysis I have run is the following:

In /group/tbi/DREAM/SST_analysis/first_level/feat_configs/

I ran feat 67_SST1aV1.fsf

The output of this is in /home/sdesimoni

**Comment by petehellyer** [comment]
I'm sure the analysis is fine - I just wanted a closer look at the logs ;)

**Comment by sdesimoni** [comment]
of course, thanks Pete

**Comment by Lmli** [comment]
Thanks for releasing it Pete.

It did start rerunning again, but now it's come up with several of the "Dependency never satisfied" comments next to some of my jobs. I think this is an error on my part because this is the log:

![screen shot 2017-06-21 at 11 59 43](https://user-images.githubusercontent.com/29597717/27380808-7d1c1ed6-5678-11e7-8263-e66a1ccc87db.png)


So, I've just killed my jobs and am going to start again :(

**Comment by Lmli** [comment]
Update:

I started a first level feat and it was running. Now it has stopped, with the "dependency never satisfied" comment. But no error noted on my report.html log.

![screen shot 2017-06-21 at 13 18 50](https://user-images.githubusercontent.com/29597717/27383722-22e3d4c0-5684-11e7-985a-771ee94e7968.png)

It appears to have stopped where it stopped previously (last week).

: I am still working on debugging my higher level feat

**Comment by Lmli** [comment]
Ok, I have fixed the bug in my higher level feet so I have set it running now. There's a lot of activity on the cluster at the moment though, so here's hoping it doesn't run into that an internal network problem again.

**Comment by sdesimoni** [comment]
I'm afraid I am having the same problem with running a dual regression. 

![screen shot 2017-06-21 at 14 33 09](https://user-images.githubusercontent.com/16757755/27387592-0a147a50-5691-11e7-9857-8bbdac3a54d1.png)

I will open another 'issue' on Github if there are more specific problems with dual regression as that will make it easier. However, I thought I would highlight the 'launch failed requeued held' problem here as it is related to the above.

**Comment by petehellyer** [comment]
Original problem with dependencies is closed - see #6  for followup on SLURM issue.

**Comment by sdesimoni** [comment]
ok thanks pete

**Comment by Lmli** [comment]
Hey... my feats are still not finished, but they all have "launch failed
requeued held" next to them... so I assume the feats are paused, not
because of a feat problem, but because the cluster is very slow/ busy
currently?

Just trying to isolate what's happening...

Thanks!

**Comment by petehellyer** [comment]
neither, there is a problem with SLURM, see #6
