### ISSUE TITLE
fslview_deprecated

### ISSUE THREAD

**Issue by celiademarchi** [c3nl-neuraldynamics/c3nl_cluster#41]
fslview_deprecated is not working :(

**Comment by celiademarchi** [comment]
NOTE:
Using the terminal to access the cluster, fslview_deprecated does not open. The error message is:
fslview_bin: cannot connect to X server localhost:18.0

If using VNC, fslview_deprecated within that does open etc.

**Comment by celiademarchi** [comment]
Any news on this? I still can't get it to work on the cluster.

**Comment by petehellyer** [comment]
This is a known issue with ssh. X11 is generally pretty unstable forwarding through ssh., The easiest way to fix this is to completely exit out of the ssh using 'exit' repeatedly until the session dies and log back in again.

Cheers

Pete

**Comment by petehellyer** [comment]
n.b. fsleyes doesnt work at all on the cluster (it will do when we have GPU's installed, but not just now)

**Comment by inesviolante** [comment]
Hi Celia,
I think this is the same issue you were having with byobu.
Try this:
1. Press fn + F2 to open a new window
2. type fslview_deprecated in that window

**Comment by celiademarchi** [comment]
Thanks Ines! That's really helpful, I'll give it a go when I'm back in the lab tomorrow.


Kind Regards,


Célia


Dr Célia Demarchi

Clinical Psychologist
The Computational, Cognitive and Clinical Neuroimaging Laboratory (C3NL): Imperial College London
Neuropsychology Service: Great Ormond Street Hospital for Children NHS Foundation Trust


________________________________

**Comment by petehellyer** [comment]
The following is a work around :)

Add this line in .bash_login before the "_byobu_source.." line:

echo $DISPLAY > $HOME/.display.env
And then add this line to .bashrc:

if [ ! -z ${SSH_CONNECTION+x} ]; then
  export DISPLAY=$(cat $HOME/.display.env) 
fi
