### ISSUE TITLE
Trying to install docker it seems we have conflicts with IPA 

### ISSUE THREAD

**Issue by eyalsoreq** [c3nl-neuraldynamics/c3nl_cluster#50]
** Found 5 pre-existing rpmdb problem(s), 'yum check' output follows:
ipa-admintools-4.4.0-14.el7.centos.7.noarch has installed conflicts freeipa-admintools: ipa-admintools-4.4.0-14.el7.centos.7.noarch
ipa-client-4.4.0-14.el7.centos.7.x86_64 has installed conflicts freeipa-client: ipa-client-4.4.0-14.el7.centos.7.x86_64
ipa-client-common-4.4.0-14.el7.centos.7.noarch has installed conflicts freeipa-client-common: ipa-client-common-4.4.0-14.el7.centos.7.noarch
ipa-common-4.4.0-14.el7.centos.7.noarch has installed conflicts freeipa-common: ipa-common-4.4.0-14.el7.centos.7.noarch
ipa-python-compat-4.4.0-14.el7.centos.7.noarch has installed conflicts freeipa-python-compat: ipa-python-compat-4.4.0-14.el7.centos.7.noarch

**Comment by eyalsoreq** [comment]
updated perl 
and then updated yum 
seemed to fix the problem

**Comment by eyalsoreq** [comment]
So installed docker - works 
However in the process I had to update pretty much everything and now sudo stopped working 
Do you think this is because of mismatch between c3nl-ds and ba23d ?

**Comment by SebastianPopescu** [comment]
thanks for installing docker! So I assume the cluster will be down until you fix the sudo issue?

**Comment by petehellyer** [comment]
What is the use case for Docker? I would usually completely veto its install in this environment.

**Comment by SebastianPopescu** [comment]
its for the brain age prediction website that James wants to create. We want to create docker images with the whole brain age prediction pipeline so people can download that image from the website and use it on their PCs

**Comment by petehellyer** [comment]
The cluster is not a suitable environment for that type of development, you should do this locally.

**Comment by SebastianPopescu** [comment]
was trying to see how docker images interact with job managers (send docker images via sbatch/qsub).

sorry for the mess caused.
