### ISSUE TITLE
Cluster matlab license issue

### ISSUE THREAD

**Issue by nsngraham** [c3nl-neuraldynamics/c3nl_cluster#53]
Hi folks,

Trying to run matlab on the cluster is now giving an error which relates to the license apparently.

Gus has also tried to load matlab and had same issue.

Would you be able to look into this please?

Many thanks

Neil 

graham@brodmann23d:~$ matlab
MATLAB is selecting SOFTWARE OPENGL rendering.
License checkout failed.
License Manager Error -15
MATLAB is unable to connect to the license server. 
Check that the license manager has been started, and that the MATLAB client machine can communicate
with the license server.

Troubleshoot this issue by visiting: 
http://www.mathworks.com/support/lme/R2016b/15

Diagnostic Information:
Feature: MATLAB 
License path: /home/ngraham/.matlab/R2016b_licenses:/apps/software/matlab/2016b/licenses/license.dat:/apps/softwar
e/matlab/2016b/licenses/network.lic 
Licensing error: -15,570. System Error: 115

**Comment by eyalsoreq** [comment]
fixed
