### ISSUE TITLE
ANTs update

### ISSUE THREAD

**Issue by GusZimmerman** [c3nl-neuraldynamics/c3nl_cluster#55]
Hi,

I am trying to run an ANTS command (ANTS and WarpImageMultiTransform) on the cluster, however it is giving me this error:
ANTS: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ANTS)
ANTS: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ANTS)
WarpImageMultiTransform: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by WarpImageMultiTransform)
WarpImageMultiTransform: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by WarpImageMultiTransform)

Doing: strings /usr/lib64/libstdc++.so.6 | grep GLIBC
we have up to GLIBCXX_3.4.19 installed, but not 3.4.20 or 3.4.21

I assume this is because an updated version is required? Would it be possible to install the latest update: https://sourceforge.net/projects/advants/

Thanks!

**Comment by petehellyer** [comment]
Use ‘module load gnu’ before hand and it should work :)

I keep meaning to add this as an automatic dependency to the ants module....

**Comment by GusZimmerman** [comment]
Working- thanks!
