### ISSUE TITLE
FSLEYES ISSUE  (X11)

### ISSUE THREAD

**Issue by nsngraham** [c3nl-neuraldynamics/c3nl_cluster#57]
HEY FOLKS

NOT SURE WHY MY CAPSLOCK IS ACTUALLY BROKEN BUT THAT IS NOT AN ISSUE FOR NOW!

I CAN RUN FSLVIEW_DEPRECATED ON CLUSTER WITH X11 RUNNING ON MY MAC FINE

BUT WHEN TRY FSLEYES  I GET THIS ERROR

ngraham@brodmann23d:~/backupsteinerpreconcat/steinerpreconcat/K98_V2$ fsleyes dti.nii.gz                                        │·······································
libGL error: No matching fbConfigs or visuals found                                                                             │·······································
libGL error: failed to load driver: swrast                                                                                      │·······································
                                                                                                                                │·······································
(fsleyes:22493): Gdk-ERROR **: The program 'fsleyes' received an X Window System error.                                         │·······································
This probably reflects a bug in the program.                                                                                    │·······································
The error was 'BadValue (integer parameter out of range for operation)'.                                                        │·······································
  (Details: serial 954 error_code 2 request_code 149 minor_code 24)                                                             │·······································
  (Note to programmers: normally, X errors are reported asynchronously;                                                         │·······································
   that is, you will receive the error a while after causing it.                                                                │·······································
   To debug your program, run it with the --sync command line                                                                   │·······································
   option to change this behavior. You can then get a meaningful                                                                │·······································
   backtrace from your debugger if you break on the gdk_x_error() function.)                                                    │·······································
/apps/software/fsl/5.0.10/bin/fsleyes: line 6: 22492 Trace/breakpoint trap   ${FSLDIR}/bin/FSLeyes/fsleyes $@                   │·······································
133 ngraham@brodmann23d:~/backupsteinerpreconcat/steinerpreconcat/K98_V2$        

WHAT DO YOU THINK?   
THANKS!

NEIL 

AND SORRY AM DEFINITELY NOT SHOUTING :-)

**Comment by nsngraham** [comment]
ngraham@brodmann23d:~/backupsteinerpreconcat/steinerpreconcat/K98_V2$ fsleyes dti.nii.gz                                        │·······································
libGL error: No matching fbConfigs or visuals found                                                                             │·······································
libGL error: failed to load driver: swrast                                                                                      │·······································
                                                                                                                                │·······································
(fsleyes:22493): Gdk-ERROR **: The program 'fsleyes' received an X Window System error.                                         │·······································
This probably reflects a bug in the program.                                                                                    │·······································
The error was 'BadValue (integer parameter out of range for operation)'.                                                        │·······································
  (Details: serial 954 error_code 2 request_code 149 minor_code 24)                                                             │·······································
  (Note to programmers: normally, X errors are reported asynchronously;                                                         │·······································
   that is, you will receive the error a while after causing it.                                                                │·······································
   To debug your program, run it with the --sync command line                                                                   │·······································
   option to change this behavior. You can then get a meaningful                                                                │·······································
   backtrace from your debugger if you break on the gdk_x_error() function.)                                                    │·······································
/apps/software/fsl/5.0.10/bin/fsleyes: line 6: 22492 Trace/breakpoint trap   ${FSLDIR}/bin/FSLeyes/fsleyes $@                   │·······································
133 ngraham@brodmann23d:~/backupsteinerpreconcat/steinerpreconcat/K98_V2$

**Comment by nsngraham** [comment]
<img width="796" alt="screen shot 2017-11-13 at 22 56 24" src="https://user-images.githubusercontent.com/12531942/32753731-e641ad08-c8c5-11e7-9cb5-74e6871d63a2.png">

**Comment by sdesimoni** [comment]
Hi Neil - not sure if this is helpful but I don't think FSLEYES works for anyone on the cluster.....

**Comment by nsngraham** [comment]
Yup - thanks Pete got back to me on that a few weeks back. Using the deprecated fslview!

Neil 

On 22 Nov 2017, at 14:22, sdesimoni <notifications@github.com> wrote:

Hi Neil - not sure if this is helpful but I don't think FSLEYES works for anyone on the cluster.....

**Comment by petehellyer** [comment]
support for fsleyes incoming, but known to be broken.
Closing for now.
