### ISSUE TITLE
issue with running matlab on compute node (non interactive session)

### ISSUE THREAD

**Issue by nsngraham** [c3nl-neuraldynamics/c3nl_cluster#60]
Hi folks,

Have been trying to run james' brain age script with Sebastian's help. 
It uses srun to process some stuff using matlab on a compute node. 

It fails at that stage however with this error:

srun: error: Task launch for 1439519.0 failed on node compute-1-2: Job credential expired
srun: error: Application launch failed: Job credential expired
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: Timed out waiting for job step to complete

For what it's worth I also have been stuggling to get matlab running on a compute node. 

I understand that previously this script was functioning well on new cluster and has not been changed.  Odd!

The script is below.

Thanks for your advice on this,

Neil

#!/bin/sh
#SBATCH -N 1
#SBATCH --cpus-per-task=1
#SBATCH --mem=5GB
#SBATCH --partition=long
#SBATCH -o spm12_preprocessing_-%A_%a.out
#SBATCH -e spm12_preprocessing_-%A_%a.err
#SBATCH -J spm12_pipeline

module load matlab
module load anaconda
module load fsl
module load brain_age

nifti_files=()
filename="$1"

while read -r line; do
    nifti_files+=("$line")
    echo "nifti file read from text - $line"
done < "$filename"

cd "$2"
echo $PWD

mkdir -p gm_data
mkdir -p wm_data
mkdir -p predictions

echo "${nifti_files[$SLURM_ARRAY_TASK_ID]}"
srun --exclusive -N1 -n1 --mem=1G bash wrap_spm_brain_age_preprocess.sh "${nifti_files[$SLURM_ARRAY_TASK_ID]}"

mv smwc1${nifti_files[$SLURM_ARRAY_TASK_ID]} ./gm_data
mv smwc2${nifti_files[$SLURM_ARRAY_TASK_ID]} ./wm_data

**Comment by Nialljb** [comment]
I also cant simply srun for interactive sessions

**Comment by petehellyer** [comment]
fixed
