### ISSUE TITLE
slurm issue- srun failing

### ISSUE THREAD

**Issue by nsngraham** [c3nl-neuraldynamics/c3nl_cluster#61]
Hi -

Related to the previous post I have found that srun is not working

eg. 

[ngraham@brodmann23d ~]$ srun echo hello
srun: error: Task launch for 1443722.0 failed on node compute-0-1: Job credential expired
srun: error: Application launch failed: Job credential expired
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.

So probably nothing specific to matlab whichi mentioned in other post.

Thanks for looking into this 
Neil

**Comment by james-cole** [comment]
I've seen that same issue with srun, seems to be something generic.
Neil, could you try using sbatch instead? This should work under some circumstances.

**Comment by nsngraham** [comment]
Hi – yup sbatch works for example if you put the commands in a script (with appropriate header info) and then sbatch nameofscript.sh

 

However there are occasions when srun is needed,  for example to create an interactive session of matlab on a compute node.

And examples of complex scripts which include srun, such as your brain age pipeline, which are more difficult to re-jig so that they run.

 

I think it is an issue for quite a few people. Pete & Eyal any thoughts on what may be underlying it?  It did work on cluster 3.0 a few months ago…

 

Best

 

Neil

**Comment by petehellyer** [comment]
fixed
