### ISSUE TITLE
DTITK_ROOT not defined

### ISSUE THREAD

**Issue by aazor** [c3nl-neuraldynamics/c3nl_cluster#7]
Hello,

After loading the dtitk module and running a few commands that worked (eg. **fsl_to_dtitk**), I tried the following command:
**dti_template_bootstrap**
I get the following error:
**Environment variable DTITK_ROOT is not defined**

I tried following instructions from this webpage for DTITK installation, and when I try running the command again I get different types of errors: **Command not found** etc..
http://dti-tk.sourceforge.net/pmwiki/pmwiki.php?n=Documentation.Install 

Please help :)
Thanks!

**Comment by eyalsoreq** [comment]
Fixed
